version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    expose:
      - '9000'
    volumes:
      - source-con-sun:/var/www/html/

  web:
    build: docker/nginx/
    ports:
      - '1758:80'
    volumes:
      - source-con-sun:/var/www/html/
    links:
      - app
    depends_on:
      - app

volumes:
  source-con-sun:

x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true
    source-con-sun:
      alpha: "."
      beta: "volume://source-con-sun"
      mode: "two-way-resolved"
      ignore:
        paths:
          - var/log/hal-app/last.logref.log
      configurationBeta:
        permissions:
          defaultFileMode: 0666
          defaultDirectoryMode: 0777
